Repository NAERO-project/front-end, pull requests merged in 2024-12, with the labels that each got.

#31 Feat/product2
  src/App.js
  src/apis/BannerApiCall.js
  src/apis/CategoryApiCall.js
  src/apis/ProductApiCall.js
  src/components/common/products/ProductMediumNav.js
  src/components/common/products/brand/BrandList.js
  src/modules/CategoryModule.js
  src/pages/admin/AdminBannerDelete.js
  src/pages/admin/AdminBannerManage.js
  src/pages/order/CartOrder.js
  src/pages/order/Order.js
  src/pages/order/css/CartOrder.module.css
  src/pages/producer/BannerManage.js
  src/pages/producer/ProductManage.js
  src/pages/products/MainListPreview.js
  src/pages/products/ProductCategory.js
  src/pages/products/ProductMore.js
Labels: bug

#32 Feat/login 이메일인증 및 css 수정
  src/apis/AuthApiCall.js
  src/apis/UserApiCall.js
  src/components/signup/SignupForm.js
  src/components/signup/UserPage.module.css
  src/modules/AuthModule.js
  src/pages/user/Signup.js
Labels: feature

#33 feat: 모니터링 프론트 완성
  src/apis/DashboardApiCall.js
  src/components/admin/Dashboard/LikedStatistics.js
  src/components/admin/Dashboard/MyResponsiveBar.js
  src/components/admin/Dashboard/MyResponsiveLine.js
  src/components/admin/Dashboard/SalesStatistics.js
  src/components/admin/Dashboard/TodayStatistics.js
  src/components/admin/Dashboard/TopLiked.js
  src/components/admin/Dashboard/TopSales.js
  src/components/admin/Dashboard/css/LikedStatistics.module.css
  src/components/admin/Dashboard/css/SalesStatistics.module.css
  src/components/admin/Dashboard/css/TodayStatistics.module.css
  src/components/admin/Dashboard/css/Top.module.css
  src/modules/DashboardModule.js
  src/pages/admin/Dashboard.js
  src/pages/admin/css/Dashboard.module.css
Labels: feature

#35 Feat/product2
  src/components/common/Footer.js
  src/components/common/MypageNav.js
  src/components/common/banner/css/SimpleBanner.module.css
  src/components/common/products/Product.js
  src/components/common/products/ProductPreviewNav.js
  src/components/common/products/brand/BrandList.js
  src/components/common/products/brand/BrandProducer.js
  src/components/common/products/brand/BrandProduct.js
  src/components/common/products/css/MainProductNav.module.css
  src/layouts/MypageLayout.js
  src/pages/Main.js
  src/pages/order/MyOrders.js
  src/pages/order/css/MyOrder.module.css
  src/pages/producer/ProductRegist.js
  src/pages/products/ProductCategory.js
  src/pages/products/ProductMore.js
  src/pages/products/brand/BrandProductCategory.js
  src/pages/products/brand/BrandProductList.js
  src/pages/products/css/ProductMore.module.css
  src/pages/questions/QuestionCreate.js
  src/pages/questions/QuestionEdit.js
  src/pages/questions/QuestionList.js
  src/pages/questions/css/QuestionCreate.module.css
  src/pages/questions/css/QuestionEdit.module.css
  src/pages/questions/css/QuestionListCSS.module.css
Labels: bug

#36 Feat/product2
  src/App.js
  src/components/common/Button.module.css
  src/components/common/products/Product.js
  src/components/common/products/brand/BrandProduct.js
  src/components/common/products/modal/BannerUpdateModal.js
  src/layouts/MypageLayout.js
  src/pages/cart/Cart.js
  src/pages/cart/css/Cart.module.css
  src/pages/order/CartOrder.js
  src/pages/order/MyOrderDetail.js
  src/pages/order/Order.js
  src/pages/order/css/CartOrder.module.css
  src/pages/order/css/OrderProductList.module.css
  src/pages/producer/BannerManage.js
  src/pages/producer/BannerRegist.js
  src/pages/producer/OrderManage.js
  src/pages/producer/ProductManage.js
  src/pages/producer/ProductRegist.js
  src/pages/producer/css/BannerManage.module.css
  src/pages/producer/css/BannerRegist.module.css
  src/pages/products/ProductDetail.js
  src/pages/products/css/ProductMore.module.css
  src/pages/questions/QuestionCreate.js
  src/pages/questions/QuestionEdit.js
  src/pages/questions/QuestionList.js
  src/pages/questions/css/QuestionEdit.module.css
  src/pages/questions/css/QuestionListCSS.module.css
Labels: bug

#37 Feat/product2
  src/components/common/admin/FilterSearchInput.js
  src/components/common/admin/FilterToggle.js
  src/components/common/admin/css/AdminFilterSearch.module.css
  src/components/common/admin/css/AdminFilterToggle.module.css
  src/components/common/admin/css/UserTableStyle.module.css
  src/pages/admin/AdminBannerManage.js
  src/pages/admin/AdminBannerUpdate.js
  src/pages/admin/manageusers/UserDetailManage.js
  src/pages/admin/manageusers/css/UserDetailManage.module.css
  src/pages/answers/AnswerList.js
  src/pages/producer/BannerRegist.js
  src/pages/producer/ProducerOrderProductList.js
  src/pages/producer/ProductRegist.js
  src/pages/producer/ProductUpdate.js
  src/pages/producer/css/BannerRegist.module.css
  src/pages/producer/css/ProductOrderProductList.module.css
  src/pages/producer/css/ProductRegist.module.css
Labels: bug

#38 Feat/product2
  src/pages/cart/Cart.js
  src/pages/cart/css/Cart.module.css
  src/pages/order/CartOrder.js
  src/pages/order/MyOrderDetail.js
  src/pages/order/MyOrders.js
  src/pages/order/Order.js
  src/pages/order/css/MyOrder.module.css
  src/pages/products/ProductCategory.js
  src/pages/products/ProductMore.js
  src/pages/products/css/MainProducer.module.css
  src/pages/products/css/ProductMore.module.css
  src/pages/questions/QuestionList.js
Labels: documentation

#40 Feat/shipping
  src/App.js
  src/apis/OrderApiCall.js
  src/components/shipping/DeliveryTrackModal.js
  src/components/shipping/DeliveryUpdateModal.js
  src/components/shipping/css/DeliveryTrackModal.module.css
  src/components/shipping/css/DeliveryUpdateModal.module.css
  src/components/shipping/css/ProducerErrorPage.module.css
  src/components/shipping/error/ProducerErrorPage.js
  src/pages/order/MyOrderDetail.js
  src/pages/producer/OrderUpdate.js
  src/pages/producer/ProducerOrderProductList.js
  src/pages/producer/css/OrderUpdate.module.css
  src/pages/producer/css/ProductOrderProductList.module.css
Labels: feature

#41 feat/monitoring: 필터링 로직 수정
  src/components/admin/Dashboard/LikedStatistics.js
  src/components/admin/Dashboard/SalesStatistics.js
  src/components/admin/Dashboard/css/LikedStatistics.module.css
  src/components/admin/Dashboard/css/SalesStatistics.module.css
Labels: bug

#43 Feat/product2
  src/components/common/Button.module.css
  src/components/common/Header.js
  src/components/common/Header.module.css
  src/components/signup/UserUpdateForm.js
  src/components/signup/css/UserUpdateForm.module.css
  src/pages/Main.js
  src/pages/admin/AdminBannerManage.js
  src/pages/admin/AdminBannerUpdate.js
  src/pages/admin/manageusers/css/AdminBannerUpdate.module.css
  src/pages/producer/BannerManage.js
  src/pages/producer/BannerRegist.js
  src/pages/products/css/ProductDetail.module.css
Labels: bug, documentation

#45 Feat/product2
  src/pages/answers/AnswerCreate.js
  src/pages/answers/AnswerDetail.js
  src/pages/answers/css/AnswerCreate.module.css
  src/pages/producer/BannerManage.js
  src/pages/producer/ProductManage.js
  src/pages/producer/ProductRegist.js
  src/pages/producer/ProductUpdate.js
  src/pages/producer/css/ProductManage.module.css
  src/pages/user/ProducerSignup.js
  src/pages/user/css/ProducerSignup.module.css
Labels: documentation
